version: "3.5"

services:
    nginx:
        restart: always
            image: nginx
            volumes:
                - ./:/var/www:ro
                - ./var/nginx:/var/log/nginx:rw
                # http://symfony.com/doc/current/setup/web_server_configuration.html#nginx
                - ./docker/front/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            ports:
                - 80:80
    engine:
        restart: always
        container_name: wecine-engine
        build:
            context: .
        env_file:
            - .env
        networks:
            - default # this network
        volumes:
            - $HOME/.composer:/.composer:rw,cached
            - $HOME/.ssh:/root/.ssh:rw,cached
            - .:/var/www:rw,cached
            - ./docker/engine/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro
            - ./var/sessions/engine:/root:rw
        environment:
            PHP_IDE_CONFIG: serverName=wecine

networks:
    default: # this network
        driver: bridge
